backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: static/images
public_folder: images
collections:
  - name: "arquitectos"
    label: "Arquitectos"
    folder: "content/arquitectos"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "hidden", default: "arquitecto_{{hour}}{{minute}}{{second}}"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "img", widget: "image",
           media_folder: '/static/images/arquitectos'}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "ciudades"
    label: "Ciudades"
    folder: "content/ciudades"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "hidden", default: "ciudad_{{hour}}{{minute}}{{second}}"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "img", widget: "image",
           media_folder: '/static/images/ciudades'}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "edificios"
    label: "Edificios"
    folder: "content/edificios"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "hidden", default: "book_{{hour}}{{minute}}{{second}}"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Ubicacion", name: "ubicacion", widget: "string"}
      - {label: "Altura", name: "altura", widget: "string"}
      - {label: "Pisos", name: "pisos", widget: "number"}
      - {label: "Arquitecto", name: "arquitectoId", widget: "relation",
          collection: "arquitectos", search_fields: ["title"], value_field: "id",
          display_fields: ["title"]}
      - {label: "Ciudad", name: "ciudadId", widget: "relation",
          collection: "ciudades", search_fields: ["title"], value_field: "id",
          display_fields: ["title"]}
      - {label: "Pisos", name: "pisos", widget: "number"}
      - {label: "Image", name: "img", widget: "image",
           media_folder: '/static/images/edificios'}
      - {label: "Body", name: "body", widget: "markdown"}